// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLCHQlbT4e1Z97FsD34weqEMUy-AV-pro',
    appId: '1:422589262010:web:07a7b9ac319e6f5c6fba83',
    messagingSenderId: '422589262010',
    projectId: 'controleabastecimento-4832f',
    authDomain: 'controleabastecimento-4832f.firebaseapp.com',
    storageBucket: 'controleabastecimento-4832f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGi0FS3SPElnHukfw5jkzsNY84tYhir7M',
    appId: '1:422589262010:android:269c9d49a05d89f26fba83',
    messagingSenderId: '422589262010',
    projectId: 'controleabastecimento-4832f',
    storageBucket: 'controleabastecimento-4832f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPyZtt1LYOCirYCJ0i7tvB6hKTWb0IwHs',
    appId: '1:422589262010:ios:fe5eb70e33f2dfe86fba83',
    messagingSenderId: '422589262010',
    projectId: 'controleabastecimento-4832f',
    storageBucket: 'controleabastecimento-4832f.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPyZtt1LYOCirYCJ0i7tvB6hKTWb0IwHs',
    appId: '1:422589262010:ios:fe5eb70e33f2dfe86fba83',
    messagingSenderId: '422589262010',
    projectId: 'controleabastecimento-4832f',
    storageBucket: 'controleabastecimento-4832f.firebasestorage.app',
    iosBundleId: 'com.example.controleAbastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLCHQlbT4e1Z97FsD34weqEMUy-AV-pro',
    appId: '1:422589262010:web:c059d21760753d666fba83',
    messagingSenderId: '422589262010',
    projectId: 'controleabastecimento-4832f',
    authDomain: 'controleabastecimento-4832f.firebaseapp.com',
    storageBucket: 'controleabastecimento-4832f.firebasestorage.app',
  );
}
